---

- name: Ensure that Apache2 is installed and update apt cache.
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Ensure that Apache2 is started and enabled at boot.
  service:
    name: apache2
    state: started
    enabled: yes

- include_tasks: settings.yml

- name: Flush handlers.
  meta: flush_handlers
